dirs:
  - .
useGitIgnore: true
ignorePatterns:
  - pattern: 'http://localhost:'
  - pattern: 'https://github.com/lewagon/'
  - pattern: 'https://www.github.com/lewagon/'
  - pattern: www.domainexemple.xyz
  - pattern: 'https://regexr.com/'
  - pattern: 'https://www.cloudflare.com/'
  - pattern: openai.com
  - pattern: 'https://mp.weixin.qq.com'
excludedDirs:
  - 04-Front-End/node_modules
aliveStatusCodes:
  - 200
  - 201
  - 204
  - 206
